### ISSUE TITLE
catalog: some menu examples don't seem to work

### ISSUE THREAD

**Issue by Thanood** [aurelia-ui-toolkits/aurelia-kendoui-bridge#439] opened 2016-03-29 09:47 UTC
The [menu event example](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/menu/events) only shows a large list of menu items and sub items. As far as I can see, there is no possible interaction (as to show events).

I don't see any console errors.

The [context menu example](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/menu/context-menu) is not displayed. There's an error this time. Stacktrace:
```
Unhandled rejection Error: No Aurelia APIs are defined for the referenced element.
    at re (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:2:21852)
    at Function.e.locateAPI (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:5:684)
    at e.createBinding (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:5:451)
    at v (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:5:16453)
    at e.create (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:6:14006)
    at e.create (http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:7:2474)
    at http://aurelia-ui-toolkits.github.io/demo-kendo/src/app-build-fd313bb28e.js:7:6456
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:31:6820)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:12229)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13032)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13733)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:15063)
    at r._fulfill (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:14104)
    at r._resolveCallback (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:10976)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:12384)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13032)
```

The same happens with these examples:
* Direction
* Orientation
* Animation effects

**Comment by adriatic** [comment] 2016-03-29 21:17
This issue seems to be more complicated than one would expect and tells me Jeroen took this bridge in "un-chartered waters" from my own viewpoint (switched to using bluebird for example). There is of course nothing wrong with that - except that I do not know how to fix it any more. 

All of the issues with the KendoUI `menu` component are caused by the same problem:

`Unhandled rejection Error: No Aurelia APIs are defined for the referenced element.`

which is created here:
```
  function getAU(element) {
    var au = element.au;

    if (au === undefined) {
      throw new Error('No Aurelia APIs are defined for the referenced element.');
    }

    return au;
  }
```

This in turn should be the result of the several missed locations where the prefix `k` should be `ak` - a relatively recent change in "namespace" we had to do in order to avoid name collisions.

#### Here is what I find confusing and why I do not know how to fix it:

**Step 1** Start by navigating to the Menu - **Basic use** sample:

![image](https://cloud.githubusercontent.com/assets/2712405/14123799/38995a4e-f5d0-11e5-83be-86f0890cd5e7.png)

observe that all seems fine in the console

**Step 2** navigate to **Api sample**

![image](https://cloud.githubusercontent.com/assets/2712405/14123900/ab3663b2-f5d0-11e5-8a05-66eac4f7a5ca.png)

Observe that there is nothing shown in the "demo section" and no error messages in the console - and there should be the warning that the `k-menu` custom element does mot exist

![image](https://cloud.githubusercontent.com/assets/2712405/14124001/3df6da42-f5d1-11e5-8832-db200e6b4a2c.png)
 
**Step 3** navigate to **Context menu sample**

Only now do I get the errors in the console - as if our app behaves "more asynchronously" (is this the bluebird's contribution)

```
Unhandled rejection Error: No Aurelia APIs are defined for the referenced element.
    at getAU (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4969:13)
    at Function.locateAPI (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:5000:24)
    at NameExpression.createBinding (http://localhost:3000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.3.0/aurelia-binding.js:4986:67)
    at applyInstructions (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:1679:36)
    at ViewFactory.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:1890:9)
    at HtmlBehaviorResource.create (http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:3451:41)
    at http://localhost:3000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.0/aurelia-templating.js:3836:18
    at r (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:31:6820)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:12229)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13032)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13733)
    at r._settlePromises (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:15063)
    at r._fulfill (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:14104)
    at r._resolveCallback (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:10976)
    at r._settlePromiseFromHandler (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:12384)
    at r._settlePromise (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13032)
    at r._settlePromise0 (https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js:30:13733)
```

### Note
This same behavior remains even if I correct the typo on [this line](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/sample/src/samples/menu/api.html#L6) - so I remain very puzzled.

**@JeroenVinke rather than just fixing this - I would really appreciate the explanation on what is happening here (in addition to `k` -> `ak` issues**

**Comment by Thanood** [comment] 2016-03-29 21:57
> Only now do I get the errors in the console - as if our app behaves "more asynchronously" (is this the bluebird's contribution)

Maybe the error is raised from one of the ```detached()``` or ```unbind()``` handlers.

**Comment by adriatic** [comment] 2016-03-29 22:52
> Maybe the error is raised from one of the detached() or unbind() handlers.

I cannot claim either way - but I do know that our bridge recognizes and warns about attempt to use unknown custom element. k-menu is such element and **until my today's experience** a typo of that type was properly reported by the bridge.

**Comment by JeroenVinke** [comment] 2016-03-30 07:13
@adriatic We use aurelia custom elements and attributes so our bridge does not throw errors differently from custom elements/attributes outside of the bridge. So i would not look into this further

**Comment by JeroenVinke** [comment] 2016-03-30 07:30
The `No Aurelia APIs are defined for the referenced element.` error is standard aurelia by the way and it is what I would expect to see

**Comment by adriatic** [comment] 2016-03-30 14:55
@JeroenVinke 
> We use aurelia custom elements and attributes so our bridge does not throw errors differently from custom elements/attributes outside of the bridge. So i would not look into this further

Would you please do me a favor and restate this sentence as I cannot make **any** sense of it.

**Comment by JeroenVinke** [comment] 2016-03-30 14:58
Our bridge does not detect that you use an unkown custom element or attribute, so the error thrown by aurelia is correct

**Comment by JeroenVinke** [comment] 2016-04-01 09:15
Fixed by @adriatic

**Closed by JeroenVinke** 2016-04-01 09:15 UTC
