### ISSUE TITLE
BindingLanguage must implement parseText

### ISSUE THREAD

**Issue by prsmith1** [aurelia-ui-toolkits/aurelia-kendoui-bridge#505] opened 2016-05-30 07:37 UTC
Hi,

I am trying to get the Kendo-ui bridge working with Kendo-pro, but am getting the following error:

DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-kendoui-bridge@0.8.1/colorpalette/colorpalette.html []

aurelia-templating.js:692 Uncaught (in promise) Error: A BindingLanguage must implement parseText(...)(…)

- parseText @ aurelia-templating.js:692

- _compileNode @ aurelia-templating.js:2008

- _compileNode @ aurelia-templating.js:2028

- compile @ aurelia-templating.js:1985

In the aurelia.use statement I am loading the plugin as:

.plugin('aurelia-kendoui-bridge', (kendo) => kendo.kendoGrid().kendoDropDownList());

Any ideas?

**Comment by adriatic** [comment] 2016-05-30 13:07
Hi @prsmith1 

The information you supplied so far is insufficient to provide any suggestions. Please check [this article](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs?category=troubleshooting&file=2._using_gists_and_gistrun) section 2.2 and provide us with the gist that behaves the same as your application.

**Comment by prsmith1** [comment] 2016-05-30 13:23
Hi @adriatic 

I should have mentioned, this occurs at application startup. I am not even trying to use any Kendo controls yet, just get my Aurelia web application set up ready to use them. I will try again with a fresh project to see if I get the same problem.

**Comment by adriatic** [comment] 2016-05-30 13:30
Rather than risking to hit the same problem again, I would suggest that you get a **[clone of this repository](https://github.com/aurelia-ui-toolkits/skeleton-plugin-kendo)** and verify that it runs. This is the standard navigation skeleton app augmented by adding a few KendoUI controls.

Since this sample was created several aurelia releases ago, you should use it only as is, without any changes that might result with version mismatch. Once you verify its correct function, then you can use that code as a template to create your own app.

**Comment by JeroenVinke** [comment] 2016-05-30 13:32
I have seeb this error before, caused by forks (jspm inspect --forks). If you have forks, try and run jspm update.

**Comment by JeroenVinke** [comment] 2016-06-01 17:57
@prsmith1 did you resolve the issue?

**Comment by prsmith1** [comment] 2016-06-02 16:47
Thanks for your response. I have downloaded skeleton-navigation-kendo and have got that all working fine, so I will use this as a starting point. I would like to get this working in an MVC 6/.Net core project, using typescript, but one step at a time :-)

**Comment by adriatic** [comment] 2016-06-02 17:03
@prsmith1 It would be great if you can keep a log of your progress - probably best in the form of an markdown file added to this issue. Could you do that?

**Comment by prsmith1** [comment] 2016-06-03 07:16
Yep no problem.

**Comment by JeroenVinke** [comment] 2016-07-30 18:34
Closing this for now. Every time this error was thrown there were JSPM forks, so if they get resolved the error most likely will be gone too

**Closed by JeroenVinke** 2016-07-30 18:34 UTC
