### ISSUE TITLE
Referencing the data item in a k-col template

### ISSUE THREAD

**Issue by Souldrinker** [aurelia-ui-toolkits/aurelia-kendoui-bridge#339] opened 2016-02-08 15:27 UTC
I was looking for a way to reference the whole data item in a k-col template. For example I did this before:
```
<tr repeat.for="service of services">
    <!--some other columns-->
    <td><book-cell service.bind="service"></book-cell></td>
</tr>
```
I can get around it by specifying a binding for each property I need to pass in to the custom component rather than the whole object as one property, but it would be nicer to be able to pass in the whole item.

@JeroenVinke suggested I should try lite this:
```
<k-col title="${'phrases.bookedtime' | t}" field="bookedTime"><book-cell service.bind="this"></book-cell></k-col>
```
...but it didn't seem to work.

**Comment by JeroenVinke** [comment] 2016-02-17 19:48
`this` in templates don't seem to work: http://plnkr.co/edit/H0Im9J?p=preview

maybe this feature can be requested for Aurelia

something else we can try is to assign the dataItem to a variable inside the context we pass onto `bind()`. We call bind [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/src/common/template-compiler.js#L134) where the `ctx` is the dataItem (the object of every row) and where $parent is the view-model

we could perhaps do something like this:

`Object.assign(ctx, { $dataItem: ctx })`

that would allow you to do this:

`<k-col title="${'phrases.bookedtime' | t}" field="bookedTime"><book-cell service.bind="$dataItem"></book-cell></k-col>`

and this:

`<k-col>${bookedTime}</k-col>`

without having to specify `dataItem` everywhere:

`<k-col>${dataItem.bookedTime}</k-col>`

One concern I have is that this may cause stackoverflows due to the circular reference we create by running `Object.assign(ctx, { $dataItem: ctx })`.

**Comment by JeroenVinke** [comment] 2016-02-19 12:53
Just tried this out, it works in general but one sample failed:

![image](https://cloud.githubusercontent.com/assets/2189477/13176130/fcf20da8-d70f-11e5-85bd-a5bc2c3b70aa.png)

**Comment by JeroenVinke** [comment] 2016-02-19 13:19
$this works in normal templates, but it doesn't work with `enhance` unfortunately (which is what we use): https://github.com/aurelia/templating/issues/270

**Comment by JeroenVinke** [comment] 2016-02-21 13:13
Closing this as  https://github.com/aurelia/templating/issues/270 has been recognized as a bug and after that has been fixed you should be able to use $this in the Grid as well

**Comment by JeroenVinke** [comment] 2016-04-15 06:06
Not a bug, we need to add the `bindingContext` to the enhance instruction

**Comment by JeroenVinke** [comment] 2016-04-27 09:09
waiting on a release of aurelia-templating so we can pass an overrideContext to enhance.

**Closed** 2016-04-30 09:38 UTC
Labels: enhancement, plugin
