### ISSUE TITLE
fix for current jspm - aurelia problems

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-kendoui-bridge#316] opened 2016-02-02 17:03 UTC
> Rob writes in his **[blog](http://blog.durandal.io/2016/02/01/big-february-status-update/)**

> There are some bugs in jspm, both 0.16 and 0.17 that we've discovered. If you are starting a new project, you are going to want to use 0.16.15 to properly install. If you already have a project that is set up with Aurelia, just make sure you are on the latest 0.16.x and you should be able to update just fine. Again, do not use 0.17.x yet.

@charlespockert and @adriatic encountered this problem - neither KendoUI master branch not Materialize branch would run missing a file that should have been loaded since it was declared as an dependency

My solution (for both KendoUI master branch and Materialize master branch:

1. set "jspm": "0.16.15" in package.json
2. run jspm dl-loader --latest
3. run npm install & jspm install & cd sample & jspm install

Note: I did this in my local repositories to verify the fix. Please update the "origins" as needed.

**Comment by charlespockert** [comment] 2016-02-02 17:04
@adriatic confirmed, this also fixed my issue with Materialize + Kendo@master

**Comment by adriatic** [comment] 2016-02-02 17:07
Note that we need a better understanding of how this all works. Few months ago I was certain to be on top of all jspm "theory" - now, I do not feel even close to be there.

**Comment by Thanood** [comment] 2016-02-02 20:05
I can't help it, running ```jspm dl-loader --latest``` downloads core-js@1.2.6 and maps it, resulting in a fork (two versions of core-js). Resolving that with ```jspm resolve --only npm_core-js@2.0.3``` leads to getting that warning again.

I'm ignoring it but I don't know if that's a good idea. Feeling the same as
> I do not live comfortably with such issues unresolved.

**Comment by adriatic** [comment] 2016-02-02 22:15
> I can't help it, running jspm dl-loader --latest downloads core-js@1.2.6 and maps it ...

I believe that you are connecting two unrelated consequences, so let me start to unravel the mystery with immediate confession that I do not know yet all I would need to know.

1. command `jspm dl-loader --latest` ensures that your local copy of JSloader is the latest that **fits** the needs of the `jspm` used for building your app.
2. you need to lock down the release number of the jspm entry in your package.json file
3. I am not sure whether you need to have your copy of `jspm` tool hat lives on your computer be also version 0.16.15, as mentioned in my previous note above. Based on today's experience, it does not seem to be necessary -- but I do not understand what is happening when you say `jspm install` when you do 1. and 2. above and your jspm tool says to be version 0.16.22 ??

**Comment by Thanood** [comment] 2016-02-02 22:39
Oh right, I didn't do 2) yet the time I wrote this.
Can that be the reason although jspm doesn't install jspm?

I will also try and downgrade my global jspm and see if it's solved.
From your comment I read that you didn't have this core-js issue.

**Comment by adriatic** [comment] 2016-02-02 23:30
The action 2. is not doing anything when running `jspm install`, but it is quite important in `jspm update` - as the "lock-down" (I want this and only this version) is what it says

**Comment by JeroenVinke** [comment] 2016-02-17 20:20
`0.16.15` seems to work fine, so i'm closing this

**Closed by JeroenVinke** 2016-02-17 20:20 UTC
