### ISSUE TITLE
Multiselect Virtualization

### ISSUE THREAD

**Issue by alexsurg** [aurelia-ui-toolkits/aurelia-kendoui-bridge#442] opened 2016-03-31 13:31 UTC
Hi,

If you go to your example of multi select virtualization:
[http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/multiselect/virtualization](http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/multiselect/virtualization)

Start typing 'er' and select the last option from the list (or any option) you can see in the debugger (Chrome for my case) that an exception is thrown:

`Uncaught TypeError: Cannot read property 'item' of undefined`

I saw the same exception in my project when i tried to use multi select.

Can you please look into it.

Thanks,
Alex

**Comment by adriatic** [comment] 2016-03-31 13:38
The current version of the example you mention should "tell you this":

![image](https://cloud.githubusercontent.com/assets/2712405/14177392/1a2316ea-f724-11e5-836a-13a0bc3f14ba.png)

Indicating that it is a known problem with KendoUI SDK,

**Comment by alexsurg** [comment] 2016-03-31 13:45
Yes, but according to the issue 368 this problem was solved in Kendo release 2016.1.226.
This is the version of Kendo that I am using but i still get errors. Also it doesnt seems that issue 368 is related to my problem because when i tried to use the multiselect in my code i didnt used template but still got the exception.

**Comment by adriatic** [comment] 2016-03-31 13:55
Leaving the final judgment to Jeroen, who is working with Telerik on several issues related to "virtualization", I will say that the reference to the issue 368 is not accurate, as I saw several recent exchanges with Telerik's support, where the remaining virtualization issue is being assigned to their specialist.

**Comment by JeroenVinke** [comment] 2016-03-31 15:07
It took quite some effort to debug, but I was able to reproduce it: http://dojo.telerik.com/adEfo

To reproduce:
1. filter the list with `er`
2. select something from the list
3. call `multiselect.value(multiselect.value())`

So basically, after you select something from the multiselect, and you try to change its value you will get this error.

You are getting this error with our bridge because:

- the widget changes its value()
- our bridge detects this and updates your view-model (due to the k-value two-way binding)
- our bridge detects that the value has changed and calls `value()` on the widget

This is something that could be improved, but I believe it is a bug in the Kendo widget and should be reported there.

I think we may be able to provide a workaround

**Comment by JeroenVinke** [comment] 2016-03-31 16:33
@alexsurg please keep an eye on https://github.com/telerik/kendo-ui-core/issues/1557.

With 0.6.3 (installable via `jspm install aurelia-kendoui-bridge`) you can disable two-way value binding like so:

```
      <ak-multiselect k-placeholder="Select addresses..."
                     k-data-text-field="ShipName"
                     k-data-value-field="OrderID"
                     k-height.bind="520"
                     k-no-value-binding.bind="true"
                     k-value.bind="[10265, 10289]"
                     k-virtual.bind="virtual"
                     k-data-source.bind="dataSource">
        <ak-template for="itemTemplate">
          <span class="order-id">${OrderID}</span>
          ${ShipName}, ${ShipCountry}
        </ak-template>
       </ak-multiselect>
```

Note the `k-no-value-binding.bind="true"`. When you need to get the value of the multiselect you can use the `k-widget`:

```
<ak-multiselect k-widget.bind="multiselect"></ak-multiselect>

someFunction() {
   let val = this.multiselect.value();
}
```

**Comment by alexsurg** [comment] 2016-03-31 17:46
Great, thanks alot for the work around i will give it a try.
I will also keep an eye on the issue that you opened to Kendo team.

**Comment by Creadigme** [comment] 2016-03-31 20:08
Hi,

For your information, same issue with DropDownList component.

It's ok with your workaround ( XXXX.widgetBase.withValueBinding = false; when the component is attached ).

Thanks

**Comment by JeroenVinke** [comment] 2016-03-31 20:21
@creadigme thanks. We accept pull requests if you feel like preparing one: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/blob/master/CONTRIBUTING.md

**Comment by JeroenVinke** [comment] 2016-04-01 06:37
@Creadigme released in 0.6.4. Install via `jspm install aurelia-kendoui-bridge`

**Comment by Leonidnei** [comment] 2016-04-05 14:32
Hi.
I tried the bypass for multiselect, however it does not show selected values in the field on the original load while when I open dropdown, the selected items are highlighted.

**Comment by JeroenVinke** [comment] 2016-04-27 09:30
This is a Kendo bug (and quite a serious one IMO), and we can't keep relying on workarounds so https://github.com/telerik/kendo-ui-core/issues/1557 is the place to be to get a fix for this issue

**Closed by JeroenVinke** 2016-04-27 09:30 UTC
