### ISSUE TITLE
Dynamic grid columns using repeat.for and ak-template

### ISSUE THREAD

**Issue by rinobatin** [aurelia-ui-toolkits/aurelia-kendoui-bridge#480] opened 2016-05-05 01:58 UTC
Hi,

I need to render dynamic grid with the data source and column metadata from the database. The column metadata contains information like column display name and data formatting (e.g. date format).

I am using `repeat.for` and `ak-template` to achieve this because some column templates are too complex  to define in the JS class. Also I would like use to Aurelia's value converter for formatting (rather than `#= kendo.toString(...) #`)  

Example: https://gist.run/?id=776edd2ced1d59a22175b746938616be

Here's the view. The `col` object is not available inside the `ak-template`. Also what is `$this` inside the ak-template? Notice that (3) works but not (2).
```
  <ak-grid k-data-source.bind="datasource">
            <ak-col repeat.for="col of columnsMetadata"  k-title="${col.title}" k-field="${col.field}" >
                <ak-template>
                    <span>col ${col.toString()}</span>
                    <div>
                       (1) ${$this[col.field]} | (2) ${$this["UnitPrice"]} | (3) ${$this.UnitPrice}
                    </div>
                </ak-template>
              
                <ak-template for="groupFooterTemplate">
                    (1) ${$this["sum"]} | (2) ${$this.UnitPrice.sum} 
                </ak-template>
                <ak-template for="footerTemplate">
                     (1) ${$this["sum"]} | (2) ${$this.sum} 
                </ak-template>

            </ak-col>
        </ak-grid>
```

**Comment by JeroenVinke** [comment] 2016-05-05 07:04
Hey @rinobatin, that's quite a complex use case you have there. Thanks for the gist.

Firstly, we have a fix going out soon for `$this`: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/9eb7908ed259ce8db731f79eb9e045f70255c185 (relevating issues: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/339 and https://github.com/aurelia/templating/issues/270). I may actually get to this today

Secondly, something i'm worried about is this issue https://github.com/aurelia/templating/issues/262. The grid uses `@children` to get a list of all `<ak-col>`'s and it will send that to the Kendo control. With  `repeat.for` you may see that the grid only renders a single column, or other weird things like that. That is going to be fixed with Aurelia's work on moving to the new Shadow DOM implementation.

**Comment by rinobatin** [comment] 2016-05-05 22:59
@JeroenVinke I guess I only have one choice at the moment -- kendo flavor. I will revisit this once those issues you mentioned are resolved. Thanks!

PS: 1 column was rendered because the columns metadata has only 1 item.

**Comment by smax48** [comment] 2016-05-06 12:34
With the latest bridge release 0.9.0, `$this` works for both (2) and (3) (in the original gist).  

Multiple columns can be rendered using `repeat.for` as well.

However, the problem is that I don't see any way to reference the `col` variable (that comes from the repeater) inside `<ak-template>`. I tried `$parent.col` but with no luck.

**Comment by JeroenVinke** [comment] 2016-05-06 14:31
[here](https://gist.run/?id=16502a95785313fa6172c9ad1a9462bd) is the gist with 0.9.0 of the bridge. 

@smax48 Yeah I don't think `col` is reachable in the `<ak-template>` either. With aurelia's templating/binding engine you can supply a bindingContext and an overrideContext. We are compiling the `<ak-template>` where the bindingContext is the dataItem of the row and where the overrideContext is the view-model where the grid is in. That way you can bind to properties on the dataItem and to properties on the view-model. There is no second overrideContext to pass the `col` variable to, so I don't know how we can implement this. I'll create an issue with the Aurelia folks, but this could be a major refactoring for them :(

**Comment by JeroenVinke** [comment] 2016-05-07 15:57
Aurelia isn't the limiting factor here. We are just not getting enough information from Kendo to be able to include the context of the `<ak-col>`.

Would something like this be a possibility? https://gist.run/?id=c6e4152a02c2d99e955a82f7110bd92f

**Comment by smax48** [comment] 2016-05-08 01:13
It is not as convenient as the "normal" Aurelia html template, but if we could use "Aurelia-style" display  value formatting, it would be better than the plain kendo... The problem here is that we must use hard coded column names, so it is no longer the "generic" template that works for any column. Anyway, I will discus this with @rinobatin to see whether it is a feasible option.

BTW, maybe a stupid question - is it possible in Aurelia and/or bridge to create a special property on ak-template with the name "context", allow bind it to some user-specific data (e.g. column metadata in our example) and then use it inside the template's html (like $context)?

**Comment by JeroenVinke** [comment] 2016-05-08 05:29
> is it possible in Aurelia and/or bridge to create a special property on ak-template with the name "context", allow bind it to some user-specific data (e.g. column metadata in our example) and then use it inside the template's html (like $context)?

Let me explain a bit what is happening here. The template in ak-template is passed to Kendo as a string. We are not compiling templates by ourselves. Kendo controls asks us whenever they need a template compiled, and the control gives us two things: the template (as string, we passed this to Kendo) and the dataItem the template should be compiled with. Unfortunately this is not enough as we need two additional things: the parent context (the view-model instance where the grid is in) and now the view-model behind ak-col which contains the `col` property. With a hack we were able to get to the parent context, but this hack isnt extensible. So we need to talk with the Telerik folks.

**Comment by smax48** [comment] 2016-05-08 06:28
Thanks for the explanation!

Today I was playing with this stuff and it seems that without support from the Kendo side there's not much we can do.
 
It is possible, however, to implement a bit "dirty" hack and do template pre-processing before it is sent to Kendo.
Inside `TemplateGatherer.useTemplates` we have almost all necessary data: parent view model & template text.
There we can do simple macro expansion using data from parent's properties. In the case of the grid column we can use something like %field% inside the template text and substitute it with the value of the `k-field` property.
I tested this and made the following working:

```
    <ak-col k-title="Contact Name" k-field="ContactName">
      <ak-template>
        ${$this['%field%'] | capitalize}
      </ak-template>
    </ak-col>
```

This is just an idea that works. The problem with this approach is that we have a bit strange syntax for templates...

**Comment by JeroenVinke** [comment] 2016-05-08 06:48
Great!! I'm not sure if we should do this by default, but what if we supplied a hook that you could implement? Then you can do this processing yourself

**Comment by smax48** [comment] 2016-05-08 06:57
Sure :) A hook would definitely solve the problem for us. Currently the only thing I changed is the mentioned `TemplateGatherer.useTemplates`. So if you could call a hook method for each template object with non-empty template, just before you assign it to the target property, that would be just great!

**Comment by JeroenVinke** [comment] 2016-05-09 17:19
@smax48 something like https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/commit/3b6d4285e5441eee00824b31477663681d7b4cb4?

**Comment by smax48** [comment] 2016-05-09 22:28
@JeroenVinke Yes, something like this. The only minor, but very important thing: I need the `target` object to be passed to the callback as well (otherwise I cannot get values for e.g. `k-field`).
Thanks a lot!

**Comment by JeroenVinke** [comment] 2016-05-11 10:30
`c` is the view-model of `<ak-col>`, which contains kField etc. I think that would be easier than parsing  `k-field` on the HTML element, am I correct?

**Comment by smax48** [comment] 2016-05-12 03:01
I thought that `c` is the view-model of `<ak-template>`... and that the view-model of `<ak-col>` is `target`.
This is the code from grid/col.js:
```
bind() {
    this.templateGatherer.useTemplates(this, 'GridColumn', this.templates);
  }
```

It seems that here `this` is the column's view-model itself.

What am I missing?...

**Comment by JeroenVinke** [comment] 2016-05-12 05:38
you're right! I'll add the target as well

**Closed** 2016-05-14 09:33 UTC

**Comment by JeroenVinke** [comment] 2016-05-15 09:06
just released this, update via `jspm install aurelia-kendoui-bridge`

Something like this should work now:
`.plugin('aurelia-kendoui-bridge', kendo => kendo.pro().withTemplateCallback((target, c, template) => template.replace('%someVar%', 'hello world'));

**Comment by smax48** [comment] 2016-05-15 09:14
Thanks! I will definitely try this!

**Comment by smax48** [comment] 2016-05-16 08:00
Tested this functionality today - everything works fine!

**Comment by dpinart** [comment] 2016-05-26 14:48
Hi,

don't understand this sentence:
```
.plugin('aurelia-kendoui-bridge', kendo => kendo.pro().withTemplateCallback((target, c, template) => template.replace('%someVar%', 'hello world'));

```
Where must it be placed? At main when configuring aurelia templates?

**Comment by adriatic** [comment] 2016-05-26 14:57
@dpinart Yes :-)

**Comment by dpinart** [comment] 2016-05-26 14:59
thanks @adriatic. What does it mean:  template.replace('%someVar%', 'hello world') ?

Sounds a bit weird

**Comment by dpinart** [comment] 2016-05-26 15:24
Any demo or example about how to create dynamic columns with repeat.for? I can't make this work

**Comment by JeroenVinke** [comment] 2016-05-26 16:12
@dpinart https://gist.run/?id=74122c67f160b321f5b95e37726f989f

I have noticed that `${%field%}` throws an error because that uncompiled template is parsed by aurelia, I need to see if we can fix that

**Comment by dpinart** [comment] 2016-05-26 17:17
I facing a weird issue, the templateCallback is being called but then the grid is creating the columns automatically by adding all properties of the inner model

**Comment by JeroenVinke** [comment] 2016-05-26 17:33
It would really help if you could reproduce it in a gist (as described [here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/free-support)). Any change that your `columnsMetadata` (out of [this gist](https://gist.run/?id=74122c67f160b321f5b95e37726f989f)) is retrieved async?

**Comment by dpinart** [comment] 2016-05-26 18:06
I was using an old version 0.7 or so. I updated to latest one (0.10.3). With this version generatin using k-columns.bind (what I'm currently using) stopped working.

**Comment by JeroenVinke** [comment] 2016-05-26 18:17
@dpinart can you open a new issue with a detailed problem description? thanks!

**Comment by smax48** [comment] 2016-05-26 23:47
@JeroenVinke Yes, `${%field%}` doesn't work with Aurelia, but in this situation it is possible to use something like this (works fine):
```
            <ak-col repeat.for="col of columns" k-title="${col.descr}" k-field="${col.name}">
                <ak-template>
                    ${$this['%k-field%']}
                </ak-template>
            </ak-col>
```

So we can use both Aurelia syntax & custom template substitution in strings

**Comment by CaptainDingle** [comment] 2017-01-12 01:27
Hello

This works fine:
`  <ak-col repeat.for="col of gridOptions[grid.DBTableName].columns" if.bind="col.dataType=='Bool'" k-width.bind="col.width" k-title.bind="col.title" k-field="${col.field}">
                        <ak-template>
                            ${$this['%field%']}
                        </ak-template>
                    </ak-col>`

But we need a way to bind that dynamic field to a checkbox in the grid (hence the use of the template). Something like this does not work:

`<input type="checkbox" value.bind="${$this['%field%']}" checked.bind="${$this['%field%']}"/>`

Is there a way to get the replacement to happen within the binding attributes for the input?

Thank you
