### ISSUE TITLE
Button's state does not update with logic not operator

### ISSUE THREAD

**Issue by Vizer** [aurelia-ui-toolkits/aurelia-kendoui-bridge#475] opened 2016-04-29 11:44 UTC
Hi guys,

I have acrossed on issue when using ak-button and disabled.bind together with logical not operator. It does not update button's state. Demo is [here](https://gist.run/?id=58f0689268ce420871d87dbd69a7b995).

Thanks,
Volodymyr

**Comment by JeroenVinke** [comment] 2016-04-29 16:08
Hey, thanks for the gist :+1: 

Seems like this happens with native kendo too: http://dojo.telerik.com/ILaPO/2

I'm not sure if this is either a bug or a missing feature in Kendo, as they probably assume you use the `enable()` function. We are thinking about adding a feature to the bridge which would allow you to two-way bind a `k-disable` or `k-enable` property which would call `.enable()` for you whenever that property changes. We are tracking this in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/414

Do you have a working workaround until we can get that feature implemented?

**Comment by Vizer** [comment] 2016-05-04 12:59
@JeroenVinke, thank you for answer. 
I will try to find some workaround.

**Comment by eliavmaman** [comment] 2016-05-05 08:30
Hey @Vizer  and @JeroenVinke 
I have the same problem with multi select.
demo i here -  https://gist.run/?id=e4f3824cc5c7dd44f35eb0734b91b2e2 (sorry from some reasone link is not working for me)
any idea?

**Comment by JeroenVinke** [comment] 2016-05-05 08:37
I just released 0.9.0 which includes the k-enabled binding: https://gist.run/?id=f3cf8c2e2e4e3e631ad0b63c428625a6

:point_up: [May 5, 2016 10:28 AM](https://gitter.im/adriatic/Aurelia-KendoUI?at=572b0412d6d0f60219f0bf0d)

**Comment by eliavmaman** [comment] 2016-05-05 08:52
@JeroenVinke  0.9.0 is the kendo bridge version?

**Comment by JeroenVinke** [comment] 2016-05-05 08:53
Yes

**Comment by eliavmaman** [comment] 2016-05-05 08:55
@JeroenVinke  `aurelia-templating-resources.js:15 Uncaught (in promise) TypeError: _aureliaPal.DOM.injectStyles is not a function(…)
`
this is what i get after upgarde...

**Comment by JeroenVinke** [comment] 2016-05-05 08:56
@eliavmaman can you join our gitter room? https://gitter.im/adriatic/Aurelia-KendoUI

**Comment by eliavmaman** [comment] 2016-05-05 08:58
i wish i could but my company does not alowd to download any thing..
![image](https://cloud.githubusercontent.com/assets/6911449/15039861/ac1a6dbe-12b8-11e6-9770-3ed73aa5e965.png)

thats what i get when trying :(

**Comment by JeroenVinke** [comment] 2016-05-05 09:00
ah, no problem. I think you have JSPM forks. You can check by running `jspm inspect --forks`. If it says that there are forks, then try running `jspm update`. Then verify if the forks are gone with `jspm inspect --forks` again

**Comment by eliavmaman** [comment] 2016-05-05 09:00
looks like `aurelia-templating-resources` has effect from the upgrade of Kendo-bridge source file.

**Comment by eliavmaman** [comment] 2016-05-05 09:08
@JeroenVinke  i did what u suggested and u r amaizing , i truly wasnt familiar with thos command.
`system.src.js:4935 GET http://localhost:63342/aurelia/public/aurelia-event-aggregator.js 404 (Not Found)`

the aurelia-event-aggregator.js is not found  now do u know anything of this error after upgrade?

**Comment by JeroenVinke** [comment] 2016-05-05 09:10
i'm not sure what needs aurelia-event-aggregator (certainly not our bridge), but you probably need to install it: `jspm install aurelia-event-aggregator`

**Comment by eliavmaman** [comment] 2016-05-05 09:14
@JeroenVinke you were right... after `jspm update` i have notice in the config file that the upgraded version is
`aurelia-kendoui-bridge": "npm:aurelia-kendoui-bridge@0.6.4` , didnt you wrote that the version supposed to be 0.9.0?

**Comment by JeroenVinke** [comment] 2016-05-05 09:16
ah, because you weren't able to open gitter you didn't get to read the message that stated that you need to run `jspm install aurelia-kendoui-bridge` to update the bridge. After that, make sure you have no forks with `jspm inspect --forks` again

**Comment by eliavmaman** [comment] 2016-05-05 12:01
@JeroenVinke  those commands

1. jspm inspect --forks
2.jspm update
are very dangerous , and  lots of things stopped working.
like 
1. custom attribute on the grid doesn't recognize grid instance 
2.grid scroll after resize is stucked and screen is jumping. 

there are few more things.
**I cant create a gist with my code bcoz my projects conatins lots of files to make every thing work and display my problem.
But i can surly tell , that i use to work with xxx version of Aurelia and bridge and when i upgrade it lot of things went wrong.**


currently i return my config file to previous state.
10x

**Comment by JeroenVinke** [comment] 2016-05-05 12:12
can you share your old config.js by posting it to [gist](https://gist.github.com/)?

**Comment by eliavmaman** [comment] 2016-05-05 12:42
done!

**Comment by JeroenVinke** [comment] 2016-05-05 12:57
thanks. Link is [here](https://gist.github.com/eliavmaman/bdb068643ba1766599a6f9f95fcf068f) for anyone else reading this. Something that's incorrect is [this line](https://gist.github.com/eliavmaman/bdb068643ba1766599a6f9f95fcf068f#file-upgraded-not-working-config-js-L34). You basically have both Kendo core and kendo pro installed. So you need to find out where that's coming from. I think you need to remove it from both package.json and config.js, then run `jspm clean`. It should say that it has removed that package.

Also, what do you mean with "custom attribute on the grid doesn't recognize grid instance ". Did you get an error? If so post that here please. About the grid jumping, I can't reproduce that [here](https://gist.run/?id=e2cdd75e548cc1c5923965ba352005d1)

**Comment by eliavmaman** [comment] 2016-05-05 13:04
will try that now and will try to upload my problem as well
10x @JeroenVinke your dedication is very apprichiated

**Comment by JeroenVinke** [comment] 2016-05-09 17:35
Closing this issue as the enable binding is now implemented: http://aurelia-ui-toolkits.github.io/demo-kendo/#/samples/datepicker/binding

**Closed by JeroenVinke** 2016-05-09 17:35 UTC
