### ISSUE TITLE
Unhandled promise rejection Error: Cannot read property 'widget' of undefined when I try to use kendo

### ISSUE THREAD

**Issue by cdaniel77** [aurelia-ui-toolkits/aurelia-kendoui-bridge#340] opened 2016-02-09 15:52 UTC
I am getting a Unhandled promise rejection Error: Cannot read property 'widget' of undefined when I try to use kendo after following the instructions on http://aurelia-ui-toolkits.github.io/demo-kendo/#/installation/vendors.

I am not using the skeleton because I don't want everything else in the skeleton.  I have the kendo js and styles folders loaded in the vendors folder at root and the config.js, main.js, and app.html files loaded properly.  In my app.html I required the two kendo files and in my nav.html I required the ./k-button.css but I still get the error.

**Comment by cdaniel77** [comment] 2016-02-09 16:11
I put all my code here http://plnkr.co/edit/phrcwRG6lLcYx5clXXJm?p=preview

**Comment by delebash** [comment] 2016-02-09 16:20
Using kendo core
Similar problem.   Unhandled promise rejection Error: Loader must implement loadTemplate(url).(…)
The  latest version of kendoui 2016.1.208 was installed after following the install instructions.  I did update the kendo path in config.js to reflect this.  I am testing the button widget using code copied directly from the example.  If needed I can post full code

**Comment by cdaniel77** [comment] 2016-02-09 16:24
@delebash, did you have to jspm install something called es6-promise...?

**Comment by adriatic** [comment] 2016-02-09 16:33
@cdaniel77 https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/340#issue-132454535

Can you please tell me what means "I am not using the skeleton ...". Which skeleton you do not want to use?

**Comment by cdaniel77** [comment] 2016-02-09 16:35
in the tutorials it is saying to download and run the [Aurelia Skeleton Navigation](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/2._setup)

**Comment by cdaniel77** [comment] 2016-02-09 16:39
@adriatic I don't follow your question, "OK, I understand now - does this completed unmodified tutorial work for you?" did you include something or are you asking if the bridge tutorial worked?

**Comment by delebash** [comment] 2016-02-09 16:43
@cdaniel77 :  No not using es6-promise.  However I am using typescript and also jquery2.2.0 since I already had that installed

**Comment by JeroenVinke** [comment] 2016-02-09 16:46
@delebash that sounds like a problem with Aurelia. Aurelia just pushed some new releases so that may have something to do with it. Can you run `jspm update` and try again?

**Comment by adriatic** [comment] 2016-02-09 16:48
@cdaniel77 sorry for not asking my question more precisely. The repository https://github.com/aurelia-ui-toolkits/skeleton-navigation-kendo contains the completed tutorial that starts **[here](http://aurelia-ui-toolkits.github.io/demo-kendo/#/help/docs/app_developers_tutorials/1._introduction)**.

My question is: did you try to clone this completed tutorial and run it locally? Answering **yes that works** would indicate that your attempt to create your application from "scratch" failed on some way. If your answer is **yes, I tried the completed tutorial and it does not work** it would allow me to start looking at your problem from a different angle.

**Comment by cdaniel77** [comment] 2016-02-09 16:51
@adriatic when I ran the skeleton tutorial I get the same exact error.  This is following the tutorial line by line and step by step.  

I did not want to use the skeleton-navigation-kendo in my current project.  I followed the tutorial where necessary and the same exact error occurred that came up with my use of the skeleton-navigation-kendo.

**Comment by adriatic** [comment] 2016-02-09 16:53
@cdaniel77 Thank you - let me run the same tutorial and find out whether I can reproduce your issue

**Comment by adriatic** [comment] 2016-02-09 17:06
@delebash https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/340#issuecomment-181938336

Hi Dan - since you think that you have the problem similar tp @cdaniel77, let's first resolve his issue so we do not deal with two possible different problems in the same thread.

**Comment by adriatic** [comment] 2016-02-09 17:09
@cdaniel77 I need to ask you one more question before I can provide you with the solution. You stated in your original problem report:

> I have the kendo js and styles folders loaded in the vendors folder at root

Tell me please where did you get kendo `js` and `styles` folder from?

**Comment by cdaniel77** [comment] 2016-02-09 18:01
Telerik, I have a company license but I am building off site so I just grabbed the latest package as of December

**Comment by JeroenVinke** [comment] 2016-02-09 18:04
@cdaniel77 what version is that?

**Comment by cdaniel77** [comment] 2016-02-09 18:06
@adriatic v2016.1.112

**Comment by JeroenVinke** [comment] 2016-02-09 18:07
@cdaniel77 That version contains a bug, which has been fixed in newer versions. We have asked Telerik to update, but in the mean time you can grab the files from [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/tree/master/vendors)

**Comment by cdaniel77** [comment] 2016-02-09 18:10
@JeroenVinke will give it a try now.  Will update when done

**Comment by cdaniel77** [comment] 2016-02-09 18:16
@JeroenVinke I tried to clone into my vendors folder but it said the path doesn't exist.  Can you zip it so I can grab it that way pls.

**Comment by JeroenVinke** [comment] 2016-02-09 18:16
@cdaniel77 you can download the zip [here](https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/archive/master.zip)

**Comment by cdaniel77** [comment] 2016-02-09 18:19
@JeroenVinke The same error occurs when I replace my vendors with that one.

**Comment by JeroenVinke** [comment] 2016-02-09 18:20
are you getting 404's, other errors?

**Comment by cdaniel77** [comment] 2016-02-09 18:21
@JeroenVinke just the initial error posted here.  The errors are coming from the es6.promise.js:150.  There are no 404s.  The network tab in Chrome is clean with no reds.

**Comment by JeroenVinke** [comment] 2016-02-09 18:24
can you perhaps join our [gitter](https://gitter.im/adriatic/Aurelia-KendoUI) channel? We can communicate a bit easier over there

**Comment by cdaniel77** [comment] 2016-02-09 18:24
Just joined.

**Comment by JeroenVinke** [comment] 2016-02-09 20:15
@delebash can you open a new issue if you still get that error? Thanks

**Closed by JeroenVinke** 2016-02-09 20:15 UTC

**Comment by delebash** [comment] 2016-02-09 20:50
jspm update worked I was on beta 1.1.1 after update all is working
